name: Go

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
      name: release linux/amd64
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.11
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          extra_files: LICENSE README.md

